# ONA config

topics:
  input:
    lidar: /livox/lidar
    imu: /livox/imu
    env: /small_room
  # output:

frames: # output frames (the transform between frames will be broadcasted)
  world: map
  body: base_link
  
num_threads: 20 # OpenMP threads (will be equal to $(nproc) if it is set higher)

sensor_type: 3  # LiDAR type (0: OUSTER \ 1: VELODYNE \ 2: HESAI \ 3: LIVOX)

debug: true     # fill useful intermediate pcl (deskewed, final_raw...) for visualizing purposes
verbose: true   # print debug/performance board

estimate_extrinsics: true   # continuous estimation of LiDAR-IMU extrinsics 
time_offset: false           # whether to take into account a possible sync offset between IMU and LiDAR (set to true if they are not properly in sync)

calibration:  # automatic IMU calibration (if all set to false, no calibration will be done)
  gravity_align: true     # estimate gravity vector
  accel: false             # estimate lin. accel. bias
  gyro: false              # estimate ang. vel. bias
  time: 0.5          # [s] time to estimate (during this time, the robot must be at stand still)

extrinsics: # w.r.t baselink [SI]
  imu:
    t: [ -0.011, -0.02329, 0.04412 ]
    R: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1. ]



  lidar:
    t: [ 0,0,0 ]
    # # # R: [ 0.774, -0.633, 0.022,
    # # #     0.633, 0.774,  -0.026,
    # # #     -0.0005, 0.03,  0.999 ] # +40º
    # # # R: [ 0.774, 0.633, -0.0005,
    # # #     -0.633, 0.774,  0.03,
    # # #     0.022, -0.026,  0.999 ] # -40º
    # R: [ 0.,  1.,  0.,
    #       -1.,  0.,  0.,
    #       0.,  0.,  1. ]

    R: [ 1.,  0.,  0.,
      0.,  1.,  0.,
      0.,  0.,  1. ]
    # t: [0, 0, -0.06334]

    # R: [ 
    #     -0.064531,  -0.703643,   0.707617,
    #     0.99738, -0.0222415,  0.0688393,
    #     -0.0326998,   0.710205,   0.703235]

    # R: [
    #     -0.0801174,  -0.704669,   0.704999,
    #     0.995952, -0.0276707,  0.0855242,
    #     -0.0407584,   0.708997,   0.704033]



intrinsics:
  accel:
    bias: [3.74305463, -0.19842248, -7.98236227]  # [m/s^2]
    sm:   [ 1.,  0.,  0.,
            0.,  1.,  0.,
            0.,  0.,  1. ]
  gyro: 
    bias: [  0.01324209, -0.01809744, -0.04366921 ]  # [rad/s]


filters:
  cropBox: # prism crop
    active: false
    box:
      min: [ -0.0, -0.0, -0.0 ]  # [m]
      max: [ 0.0, 0.0, 0.0 ]     # [m]

  voxelGrid:
    active: true
    leafSize: [0.1 , 0.1, 0.1]
    small_room_leafSize: [0.1, 0.1, 0.1]
    medium_room_leafSize: [0.1, 0.1, 0.1]
    button_trigger: false

  minDistance: # sphere crop
    active: true
    value: 0.0  # [m]

  FoV: # crop field of view
    active: false
    value: 360  # [deg]
  
  rateSampling: # quick downsample
    active: true
    value: 1

iKFoM:  # Iterative Kalman Filter on Manifolds lib
  MAX_NUM_ITERS: 2                # max num+1 of iterations of the KF (limits comp. load)
  MAX_NUM_MATCHES: 5000           # max num of matches to account for when computing Jacobians (limits comp. load)
  MAX_NUM_PC2MATCH: 1.e+4         # max num of points to consider when matching with map (limits comp. load)
  LIMITS: 0.001           

  Mapping:
    
    NUM_MATCH_POINTS: 5          # num of points that constitute a match
    MAX_DIST_PLANE: 2.0      # [m] max distance between points of every match
    PLANES_THRESHOLD: 2.5e-2      # [m] threshold to consider if match points are part of a plane 
    LocalMapping: true            # whether to keep a fixed size map (moving with the robot) or a limitless map (when active, it limits the memory in use)

  iKDTree: # Incremental KD Tree lib
    balance: 0.6      # tree balancing param (higher value improves search range and rebalances the tree more often)
    delete: 0.3       # tree deletion param (high value reduces the tree size)
    voxel: 0.1        # downsampling value
    bb_size: 300.0    # [m] Local Map's bounding box dimension
    bb_range: 50.0    # [m] Local Map's bounding box moving range (if the robot is closer than bb_range to any local map edge, the BB will move)

  covariance:
    # gyro: 0.0001 
    # accel: 0.01
    # bias_gyro: 0.000001
    # bias_accel: 0.0001
    gyro: 0.25
    accel: 0.5
    bias_gyro: 0.000266
    bias_accel: 0.0043





  esekf:
    # Original Method (Information Matrix):
    # Amount of information/certainty available in each direction
    # Higher values = More information = More certainty
    # Lower values = Less information = Potential degeneracy
  # Selective Method (Covariance Matrix):
    # Amount of variance/uncertainty in each direction
    # Higher values = More uncertainty = Potential degeneracy
    # Lower values = Less uncertainty = More certainty
    active: true
    change_according_to_env: false   #works only if button trigge
    default:
      # measurement_noise: 0.0001
      # degeneracy_threshold: 0.01
      measurement_noise: 0.0001
      degeneracy_threshold: 10.0
      print_degeneracy_values: false
    small_room:
      measurement_noise: 0.0001
      degeneracy_threshold: 10.0
      print_degeneracy_values: false
    medium_room:
      measurement_noise: 0.0001
      degeneracy_threshold: 1.0
      print_degeneracy_values: false

  # covariance:
  #   gyro: 0.25
  #   accel: 0.5
  #   bias_gyro: 0.000266
  #   bias_accel: 0.0043

save:
  dense_pcd: true
  skewed_pcd: true
  break_pcd_on_service_call: true           


offline_mode: true
scan_path: "/media/inkers/Extreme SSD/HiraNandini_Mid/26_FEB_CP00000_Basement-2_HIRANANDANI_HIGHLAND_MUMBAI_PART_B_MID_RUN_2_15_15_15"
# scan_path: /media/inkers/Disk_2TB_SSD/08_FEB_CP00000_FL0_UKN_BELVEDAR_TEST_RUN_14_44_30
# scan_path: /media/inkers/Disk_2TB_SSD/29_JAN_CP00000_FL6_ETV_HOTEL_R1_15_23_04